### ISSUE TITLE
Call function from URL

### ISSUE THREAD

**Issue by lmmartinm** [anirudhgarg/functions-logicapp-startstopvms#1]
Hello there

I am using startstopvms with success.
Getting the function URL says it is:

**https://FUNCTIONNAME.azurewebsites.net/api/StartStopVMs**

which shows:

`<string>Error parsing input, Error:Object reference not set to an instance of an object., Usage is: {"subscriptionId":"<subscriptionid>", "mode":"start|stop", ["resourceGroupName":"<resourceGroupName>"], ["tag":"<tag>"], ["batchsize":"<batchsize>"]}</string>`

I would like to call the function from CURL and trying::

`curl -X POST --data "subscriptionId=SUBID&mode=stop&resourceGroupName=RG&tag=stopat19&batchsize=10" https://FUNCTIONNAME.azurewebsites.net/api/StartStopVMs/run?`

Response is none, but seems i am not on the correct way. Do you know if i am doing something wrong?

Thanks in advance.

Best regards

**Comment by anirudhgarg** [comment]
Hi @lmmartinm sorry for the very late reply. I am glad to know that you are able to use it. You just need to pass the data in JSON format. So try to format the string in JSON format and try it. 

{"subscriptionId":"<subscriptionid>", "mode":"start|stop", ["resourceGroupName":"<resourceGroupName>"], ["tag":"<tag>"], ["batchsize":"<batchsize>"]}

**Comment by anirudhgarg** [comment]
I am closing this issue. Let me know if you were not able to do this.
